version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - '5173:5173'
    environment:
      - NODE_ENV=development

